class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDQAAADIwMTkyNjc1NjYzMDRxAlgGAAAAY3VkYTowcQNLBk50cQRRLoACXXEAWA0AAAAy
    MDE5MjY3NTY2MzA0cQFhLgYAAAAAAAAAHPALQPRZEUBQzu0/UV0nQIV2AkACtoo+
- 0
- !!python/tuple
  - 6
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
learning_rate: 0.001
model_name: gru
model_params:
  dropout: 0.3
  hidden_size: 128
  num_layers: 2
weight_decay: 0.0001
